name: Yaml Lint Test
on:
    push:
      branches:
        - master
    workflow_dispatch:
        branches: [ master ]   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: echo env enviorment variables
        run: |
           echo CI $CI GITHUB_WORKFLOW $GITHUB_WORKFLOW GITHUB_RUN_ID $GITHUB_RUN_ID
           echo GITHUB_RUN_NUMBER $GITHUB_RUN_NUMBER GITHUB_ACTION $GITHUB_ACTION GITHUB_ACTIONS $GITHUB_ACTIONS
           echo GITHUB_ACTOR $GITHUB_ACTOR GITHUB_REPOSITORY $GITHUB_REPOSITORY GITHUB_EVENT_NAME $GITHUB_EVENT_NAME
           echo GITHUB_EVENT_PATH $GITHUB_EVENT_PATH GITHUB_WORKSPACE $GITHUB_WORKSPACE GITHUB_SHA $GITHUB_SHA
           echo GITHUB_REF $GITHUB_REF GITHUB_HEAD_REF $GITHUB_HEAD_REF GITHUB_BASE_REF $GITHUB_BASE_REF
           echo GITHUB_SERVER_URL $GITHUB_SERVER_URL GITHUB_API_URL $GITHUB_API_URL GITHUB_GRAPHQL_URL $GITHUB_GRAPHQL_URL

      - uses: actions/checkout@master

      - name: Self test valid
        id: selftestValid
        uses: briegel0/gha-lint-yaml@master
        with:
          path: "tests/valid.yaml"
      - name: Check outputs and modified files Valid
        run: |
          echo "The warnings is ${{ steps.selftestValid.outputs.warnings }}"
          echo "The errors is ${{ steps.selftestValid.outputs.errors }}"
          test "${{ steps.selftestValid.outputs.warnings }}" == "0"
          test "${{ steps.selftestValid.outputs.errors }}" == "0"  

      - name: Self test valid Warning
        id: selftestWarning
        uses: briegel0/gha-lint-yaml@master
        with:
          path: "tests/validwarning.yaml"

      - name: Check outputs and modified files ValidWarning
        run: |
            echo "The warnings is ${{ steps.selftestWarning.outputs.warnings }}"
            echo "The errors is ${{ steps.selftestWarning.outputs.errors }}"
            test "${{ steps.selftestWarning.outputs.warnings }}" == "1"  
            test "${{ steps.selftestWarning.outputs.errors }}" == "0"  

      - name: Self test Invalid                 
        id: selftestInValid
        uses: briegel0/gha-lint-yaml@master
        with:
          path: "tests/invalid.yaml"
      - name: Check outputs and modified files InValid
        run: |
          echo "The warnings is ${{ steps.selftestInValid.outputs.warnings }}"
          echo "The errors is ${{ steps.selftestInValid.outputs.errors }}"
          test "${{ steps.selftestInValid.outputs.errors }}" == "1"          
          