name: Yaml Lint Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Self test valid
        id: selftestValid
        uses: briegel0/gha-lint-yaml@master
        with:
          path: "tests/valid.yaml"
      - name: Check outputs and modified files Valid
        run: |
          echo "The warnings is ${{ steps.selftestValid.outputs.warnings }}"
          echo "The errors is ${{ steps.selftestValid.outputs.errors }}"
          test "${{ steps.selftestValid.outputs.warnings }}" == "0"
          test "${{ steps.selftestValid.outputs.errors }}" == "0"  

      - name: Self test valid Warning
        id: selftestWarning
        uses: briegel0/gha-lint-yaml@master
        with:
          path: "tests/validwarning.yaml"

      - name: Check outputs and modified files ValidWarning
        run: |
            echo "The warnings is ${{ steps.selftestWarning.outputs.warnings }}"
            echo "The errors is ${{ steps.selftestWarning.outputs.errors }}"
            test "${{ steps.selftestWarning.outputs.warnings }}" == "1"  selftestWarning
            test "${{ steps.selftestWarning.outputs.errors }}" == "0"  
             
      - name: Self test Invalid                 
        id: selftestInValid
        uses: briegel0/gha-lint-yaml@master
        with:
          path: "tests/invalid.yaml"
      - name: Check outputs and modified files InValid
        run: |
          echo "The warnings is ${{ steps.selftestInValid.outputs.warnings }}"
          echo "The errors is ${{ steps.selftestValid.outputs.errors }}"
          test "${{ steps.selftestInValid.outputs.errors }}" == "1"          
          